/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sims */
        get: operations["list_sims_api_sims_get"];
        put?: never;
        /**
         * Create And Start
         * @description Create a simulation row (IDLE).
         *
         *     When ``payload.start`` is True, also spawn the run via
         *     :class:`SimulationManager`. ``start`` defaults to False, preserving the
         *     M3a contract that plain creation does not spawn a task.
         */
        post: operations["create_and_start_api_sims_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sims/{sim_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sim */
        get: operations["get_sim_api_sims__sim_id__get"];
        put?: never;
        post?: never;
        /** Delete Sim */
        delete: operations["delete_sim_api_sims__sim_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sims/{sim_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause Sim
         * @description Pause a sim. When it is running in this manager the cooperative pause
         *     flag is used (the manager writes the DB status); otherwise fall back to a
         *     direct status flip so imported/idle rows still respond.
         */
        post: operations["pause_sim_api_sims__sim_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sims/{sim_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Sim */
        post: operations["resume_sim_api_sims__sim_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sims/{sim_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Sim */
        post: operations["stop_sim_api_sims__sim_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sims/{sim_id}/steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Steps */
        get: operations["list_steps_api_sims__sim_id__steps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sims/{sim_id}/steps/{step}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Step */
        get: operations["get_step_api_sims__sim_id__steps__step__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sims/{sim_id}/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Personas */
        get: operations["list_personas_api_sims__sim_id__personas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sims/{sim_id}/personas/{name}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Persona State */
        get: operations["persona_state_api_sims__sim_id__personas__name__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sims/{sim_id}/personas/{name}/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Persona Memory */
        get: operations["persona_memory_api_sims__sim_id__personas__name__memory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sims/{sim_id}/llm-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Llm Logs */
        get: operations["list_llm_logs_api_sims__sim_id__llm_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sims/{sim_id}/llm-logs/{call_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Llm Log */
        get: operations["get_llm_log_api_sims__sim_id__llm_logs__call_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/effective": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Effective Config
         * @description Return the resolved runtime configuration with secrets redacted.
         */
        get: operations["effective_config_api_config_effective_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sims/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Sim */
        post: operations["import_sim_api_sims_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sims/{sim_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Sim */
        post: operations["export_sim_api_sims__sim_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sims/import/forks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Forks */
        get: operations["list_forks_api_sims_import_forks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Profiles */
        get: operations["list_profiles_api_llm_profiles_get"];
        put?: never;
        /** Create Profile */
        post: operations["create_profile_api_llm_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm-profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Profile */
        put: operations["update_profile_api_llm_profiles__profile_id__put"];
        post?: never;
        /** Delete Profile */
        delete: operations["delete_profile_api_llm_profiles__profile_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm-profiles/{profile_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Profile */
        post: operations["test_profile_api_llm_profiles__profile_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Personas
         * @description Walk the bundled persona directories and summarise each one.
         */
        get: operations["list_personas_api_meta_personas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Maps
         * @description Scan ``<assets>/maze/*`` and surface each map's meta + visuals URL.
         */
        get: operations["list_maps_api_meta_maps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** EffectiveConfigOut */
        EffectiveConfigOut: {
            /** Database Url */
            database_url: string;
            /** Assets Dir */
            assets_dir: string;
            /** Logs Dir */
            logs_dir: string;
            /** Frontend Dev Origin */
            frontend_dev_origin: string;
            /** Secret Key Present */
            secret_key_present: boolean;
            /** Llm Profiles Count */
            llm_profiles_count: number;
        };
        /** ExportRequest */
        ExportRequest: {
            /** Target Dir */
            target_dir: string;
            /**
             * Layout
             * @default compressed
             * @enum {string}
             */
            layout: "compressed" | "live";
        };
        /** ExportResponse */
        ExportResponse: {
            /** Sim Id */
            sim_id: number;
            /** Sim Code */
            sim_code: string;
            /** Output Path */
            output_path: string;
        };
        /** ForkInfo */
        ForkInfo: {
            /** Sim Code */
            sim_code: string;
            /**
             * Source
             * @enum {string}
             */
            source: "compressed_storage" | "storage" | "db";
            /** Path */
            path: string;
            /** Persona Names */
            persona_names?: string[];
            /**
             * Step Count
             * @default 0
             */
            step_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Version */
            version: string;
        };
        /** ImportRequest */
        ImportRequest: {
            /** Source Path */
            source_path: string;
            /** Sim Code Override */
            sim_code_override?: string | null;
            /**
             * On Conflict
             * @default fail
             * @enum {string}
             */
            on_conflict: "fail" | "replace" | "skip";
        };
        /** ImportResponse */
        ImportResponse: {
            /** Sim Id */
            sim_id: number;
            /** Sim Code */
            sim_code: string;
            /** Counts */
            counts: {
                [key: string]: number;
            };
        };
        /** LlmCallDetail */
        LlmCallDetail: {
            /** Id */
            id: number;
            /** Persona Name */
            persona_name: string | null;
            /** Step */
            step: number | null;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Model */
            model: string;
            /** Provider */
            provider: string;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Latency Ms */
            latency_ms: number;
            /** Error */
            error: string | null;
            /** Prompt */
            prompt: string;
            /** Response */
            response: string;
        };
        /** LlmCallSummary */
        LlmCallSummary: {
            /** Id */
            id: number;
            /** Persona Name */
            persona_name: string | null;
            /** Step */
            step: number | null;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Model */
            model: string;
            /** Provider */
            provider: string;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Latency Ms */
            latency_ms: number;
            /** Error */
            error: string | null;
        };
        /** LlmLogsListOut */
        LlmLogsListOut: {
            /** Items */
            items: components["schemas"]["LlmCallSummary"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** LlmProfileCreate */
        LlmProfileCreate: {
            /** Name */
            name: string;
            /**
             * Provider
             * @enum {string}
             */
            provider: "openai" | "deepseek" | "anthropic";
            /** Model */
            model: string;
            /** Api Key */
            api_key: string;
            /** Base Url */
            base_url?: string | null;
            /**
             * Max Tokens
             * @default 4096
             */
            max_tokens: number;
            /**
             * Temperature
             * @default 0.5
             */
            temperature: number;
            /** Extra */
            extra?: Record<string, never> | null;
        };
        /** LlmProfileOut */
        LlmProfileOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Base Url */
            base_url: string | null;
            /** Max Tokens */
            max_tokens: number;
            /** Temperature */
            temperature: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LlmProfileTestResult */
        LlmProfileTestResult: {
            /** Ok */
            ok: boolean;
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Model */
            model: string;
            /** Sample Response */
            sample_response?: string | null;
            /** Error */
            error?: string | null;
        };
        /** LlmProfileUpdate */
        LlmProfileUpdate: {
            /** Name */
            name?: string | null;
            /** Provider */
            provider?: ("openai" | "deepseek" | "anthropic") | null;
            /** Model */
            model?: string | null;
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Max Tokens */
            max_tokens?: number | null;
            /** Temperature */
            temperature?: number | null;
            /** Extra */
            extra?: Record<string, never> | null;
        };
        /** MapMetaItem */
        MapMetaItem: {
            /** Name */
            name: string;
            /** Visuals Url */
            visuals_url: string;
            /** Meta */
            meta: Record<string, never>;
            /** Sprite Sheet Url */
            sprite_sheet_url?: string | null;
        };
        /** MemoryListOut */
        MemoryListOut: {
            /** Items */
            items: components["schemas"]["MemoryNodeOut"][];
            /** Total */
            total: number;
        };
        /** MemoryNodeOut */
        MemoryNodeOut: {
            /** Id */
            id: number;
            /** Node Id */
            node_id: string;
            /** Node Type */
            node_type: string;
            /** Created */
            created: number;
            /** Expiration Step */
            expiration_step: number | null;
            /** Subject */
            subject: string;
            /** Predicate */
            predicate: string;
            /** Object */
            object: string;
            /** Description */
            description: string;
            /** Poignancy */
            poignancy: number;
            /** Keywords */
            keywords?: string[];
        };
        /** PersonaMetaItem */
        PersonaMetaItem: {
            /** Name */
            name: string;
            /** Age */
            age?: number | null;
            /** Has Sprite */
            has_sprite: boolean;
            /** Bootstrap Set */
            bootstrap_set: string;
        };
        /** PersonaOut */
        PersonaOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Age */
            age: number | null;
            /** Plan Text */
            plan_text: string | null;
        };
        /** PersonaStateOut */
        PersonaStateOut: {
            persona: components["schemas"]["PersonaOut"];
            /** Scratch */
            scratch: Record<string, never> | null;
            /** Spatial Memory */
            spatial_memory: Record<string, never> | null;
            /** Recent Memory */
            recent_memory: components["schemas"]["MemoryNodeOut"][];
            /** Step */
            step: number;
            /** Curr Time Iso */
            curr_time_iso: string | null;
        };
        /** SimulationCreateIn */
        SimulationCreateIn: {
            /** Sim Code */
            sim_code: string;
            /** Fork Sim Code */
            fork_sim_code?: string | null;
            /** Personas */
            personas?: string[];
            /** Inner Voice */
            inner_voice?: string | null;
            /** Idea */
            idea?: string | null;
            /**
             * N Round
             * @default 200
             */
            n_round: number;
            /**
             * Start Hms
             * @default 07:00:00
             */
            start_hms: string;
            /**
             * Sec Per Step
             * @default 10
             */
            sec_per_step: number;
            /**
             * Maze Name
             * @default the_ville
             */
            maze_name: string;
            /** Llm Profile Id */
            llm_profile_id?: number | null;
            /**
             * Start
             * @default false
             */
            start: boolean;
        };
        /** SimulationOut */
        SimulationOut: {
            /** Id */
            id: number;
            /** Sim Code */
            sim_code: string;
            /** Fork Sim Code */
            fork_sim_code: string | null;
            /** Status */
            status: string;
            /** Start Time Iso */
            start_time_iso: string;
            /** Curr Time Iso */
            curr_time_iso: string;
            /** Sec Per Step */
            sec_per_step: number;
            /** Step */
            step: number;
            /** Maze Name */
            maze_name: string;
            /** N Round */
            n_round: number;
            /** Investment */
            investment: number;
            /** Error Message */
            error_message: string | null;
            /** Deleted */
            deleted: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** StepListOut */
        StepListOut: {
            /** Items */
            items: components["schemas"]["StepMovementOut"][];
            /** Total */
            total: number;
            /** From Step */
            from_step: number;
            /** To Step */
            to_step: number;
        };
        /** StepMovementOut */
        StepMovementOut: {
            /** Step */
            step: number;
            /** Persona Name */
            persona_name: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Description */
            description: string | null;
            /** Pronunciatio */
            pronunciatio: string | null;
            /** Chat */
            chat?: unknown[] | null;
            /** Location Path */
            location_path: string | null;
        };
        /** StepSnapshotOut */
        StepSnapshotOut: {
            /** Step */
            step: number;
            /** Environment */
            environment: Record<string, never> | null;
            /** Movements */
            movements: components["schemas"]["StepMovementOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    list_sims_api_sims_get: {
        parameters: {
            query?: {
                status?: string | null;
                include_deleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_and_start_api_sims_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sim_api_sims__sim_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sim_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_sim_api_sims__sim_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sim_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_sim_api_sims__sim_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sim_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_sim_api_sims__sim_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sim_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_sim_api_sims__sim_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sim_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_steps_api_sims__sim_id__steps_get: {
        parameters: {
            query?: {
                from?: number | null;
                to?: number | null;
            };
            header?: never;
            path: {
                sim_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_step_api_sims__sim_id__steps__step__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sim_id: number;
                step: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepSnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_personas_api_sims__sim_id__personas_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sim_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    persona_state_api_sims__sim_id__personas__name__state_get: {
        parameters: {
            query?: {
                step?: number | null;
                k?: number;
            };
            header?: never;
            path: {
                sim_id: number;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    persona_memory_api_sims__sim_id__personas__name__memory_get: {
        parameters: {
            query?: {
                type?: string | null;
                before_step?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                sim_id: number;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_llm_logs_api_sims__sim_id__llm_logs_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                persona?: string | null;
                model?: string | null;
            };
            header?: never;
            path: {
                sim_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmLogsListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_llm_log_api_sims__sim_id__llm_logs__call_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sim_id: number;
                call_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmCallDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    effective_config_api_config_effective_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EffectiveConfigOut"];
                };
            };
        };
    };
    import_sim_api_sims_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_sim_api_sims__sim_id__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sim_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_forks_api_sims_import_forks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForkInfo"][];
                };
            };
        };
    };
    list_profiles_api_llm_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmProfileOut"][];
                };
            };
        };
    };
    create_profile_api_llm_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LlmProfileCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_api_llm_profiles__profile_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LlmProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_profile_api_llm_profiles__profile_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_profile_api_llm_profiles__profile_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmProfileTestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_personas_api_meta_personas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaMetaItem"][];
                };
            };
        };
    };
    list_maps_api_meta_maps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapMetaItem"][];
                };
            };
        };
    };
}
