"""initial schema

Revision ID: d487ca4d1053
Revises: 
Create Date: 2026-05-13 12:07:10.547086+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd487ca4d1053'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('k', sa.String(length=128), nullable=False),
    sa.Column('v', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('llm_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('api_key', sa.LargeBinary(), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('extra_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("provider IN ('openai', 'deepseek', 'anthropic')", name='ck_llm_profiles_provider'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sim_code', sa.String(length=255), nullable=False),
    sa.Column('fork_sim_code', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_time_iso', sa.String(length=64), nullable=False),
    sa.Column('curr_time_iso', sa.String(length=64), nullable=False),
    sa.Column('sec_per_step', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('maze_name', sa.String(length=64), nullable=False),
    sa.Column('idea', sa.Text(), nullable=True),
    sa.Column('inner_voice', sa.Text(), nullable=True),
    sa.Column('n_round', sa.Integer(), nullable=False),
    sa.Column('investment', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('idle', 'running', 'paused', 'completed', 'failed', 'interrupted', 'stopped')", name='ck_simulations_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sim_code')
    )
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulations_deleted'), ['deleted'], unique=False)

    op.create_table('llm_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sim_id', sa.Integer(), nullable=False),
    sa.Column('persona_name', sa.String(length=128), nullable=True),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sim_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.create_index('ix_llm_calls_sim_ts', ['sim_id', 'ts'], unique=False)

    op.create_table('personas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sim_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('plan_text', sa.Text(), nullable=True),
    sa.Column('scratch_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sim_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sim_id', 'name', name='uq_personas_sim_name')
    )
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personas_sim_id'), ['sim_id'], unique=False)

    op.create_table('simulation_config_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sim_id', sa.Integer(), nullable=False),
    sa.Column('llm_profile_json', sa.JSON(), nullable=False),
    sa.Column('persona_filter_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sim_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sim_id')
    )
    op.create_table('step_environments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sim_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['sim_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sim_id', 'step', name='uq_step_environments_sim_step')
    )
    with op.batch_alter_table('step_environments', schema=None) as batch_op:
        batch_op.create_index('ix_step_environments_sim_step', ['sim_id', 'step'], unique=False)

    op.create_table('step_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sim_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('persona_name', sa.String(length=128), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pronunciatio', sa.String(length=32), nullable=True),
    sa.Column('chat_json', sa.JSON(), nullable=True),
    sa.Column('location_path', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['sim_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sim_id', 'step', 'persona_name', name='uq_step_movements_sim_step_persona')
    )
    with op.batch_alter_table('step_movements', schema=None) as batch_op:
        batch_op.create_index('ix_step_movements_sim_step', ['sim_id', 'step'], unique=False)

    op.create_table('memory_keywords_to_chat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id', 'keyword', 'node_id', name='uq_mkw_chat_persona_kw_node')
    )
    with op.batch_alter_table('memory_keywords_to_chat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_keywords_to_chat_keyword'), ['keyword'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_keywords_to_chat_persona_id'), ['persona_id'], unique=False)

    op.create_table('memory_keywords_to_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id', 'keyword', 'node_id', name='uq_mkw_event_persona_kw_node')
    )
    with op.batch_alter_table('memory_keywords_to_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_keywords_to_event_keyword'), ['keyword'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_keywords_to_event_persona_id'), ['persona_id'], unique=False)

    op.create_table('memory_keywords_to_thought',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id', 'keyword', 'node_id', name='uq_mkw_thought_persona_kw_node')
    )
    with op.batch_alter_table('memory_keywords_to_thought', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_keywords_to_thought_keyword'), ['keyword'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_keywords_to_thought_persona_id'), ['persona_id'], unique=False)

    op.create_table('memory_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('node_type', sa.String(length=16), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('type_count', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('expiration_step', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('predicate', sa.String(length=255), nullable=False),
    sa.Column('object', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('poignancy', sa.Integer(), nullable=False),
    sa.Column('keywords_json', sa.JSON(), nullable=False),
    sa.Column('filling_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("node_type IN ('event', 'thought', 'chat')", name='ck_memory_nodes_node_type'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id', 'node_id', name='uq_memory_nodes_persona_node')
    )
    with op.batch_alter_table('memory_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_nodes_persona_id'), ['persona_id'], unique=False)
        batch_op.create_index('ix_memory_nodes_persona_type_created', ['persona_id', 'node_type', 'created'], unique=False)

    op.create_table('spatial_memory_trees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('tree_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spatial_memory_trees')
    with op.batch_alter_table('memory_nodes', schema=None) as batch_op:
        batch_op.drop_index('ix_memory_nodes_persona_type_created')
        batch_op.drop_index(batch_op.f('ix_memory_nodes_persona_id'))

    op.drop_table('memory_nodes')
    with op.batch_alter_table('memory_keywords_to_thought', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_keywords_to_thought_persona_id'))
        batch_op.drop_index(batch_op.f('ix_memory_keywords_to_thought_keyword'))

    op.drop_table('memory_keywords_to_thought')
    with op.batch_alter_table('memory_keywords_to_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_keywords_to_event_persona_id'))
        batch_op.drop_index(batch_op.f('ix_memory_keywords_to_event_keyword'))

    op.drop_table('memory_keywords_to_event')
    with op.batch_alter_table('memory_keywords_to_chat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_keywords_to_chat_persona_id'))
        batch_op.drop_index(batch_op.f('ix_memory_keywords_to_chat_keyword'))

    op.drop_table('memory_keywords_to_chat')
    with op.batch_alter_table('step_movements', schema=None) as batch_op:
        batch_op.drop_index('ix_step_movements_sim_step')

    op.drop_table('step_movements')
    with op.batch_alter_table('step_environments', schema=None) as batch_op:
        batch_op.drop_index('ix_step_environments_sim_step')

    op.drop_table('step_environments')
    op.drop_table('simulation_config_snapshots')
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personas_sim_id'))

    op.drop_table('personas')
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_index('ix_llm_calls_sim_ts')

    op.drop_table('llm_calls')
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulations_deleted'))

    op.drop_table('simulations')
    op.drop_table('llm_profiles')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
